services:
  command-center:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: command-center
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./config:/app/config:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/hostname:/host/etc/hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - COMMAND_CENTER_NETWORK=192.168.50.0/24
      - COMMAND_CENTER_INTERFACE=enp3s0
    restart: unless-stopped
  command-center-ui:
    build:
      context: .
      dockerfile: frontend-react/Dockerfile
    container_name: command-center-ui
    network_mode: host
    restart: unless-stopped